### ISSUE TITLE
Incorrect symbol for minute

### ISSUE THREAD

**Issue by sergiqp** [stuartlangridge/ambient-ubuntu-phone#1]
When selecting an interval of time to finish the sound it shows the interval in the format '1hour 30m'.

Because 'm' is the symbol for 'metre' and the symbol for 'minute' is 'min', I think it should be shown in one of these formats: '1 hour 30 minutes' or '1h 30min'.

You have more information in this other bug: https://bugs.launchpad.net/unav/+bug/1558732

Thanks for your app!

**Comment by stuartlangridge** [comment]
Closed in 1.3 release.
